[uf1_idx]
coldPath = $SPLUNK_DB/uf1_idx/colddb
homePath = $SPLUNK_DB/uf1_idx/db
thawedPath = $SPLUNK_DB/uf1_idx/thaweddb

[uf2_idx]
coldPath = $SPLUNK_DB/uf2_idx/colddb
homePath = $SPLUNK_DB/uf2_idx/db
thawedPath = $SPLUNK_DB/uf2_idx/thaweddb

[uf3_idx]
coldPath = $SPLUNK_DB/uf3_idx/colddb
homePath = $SPLUNK_DB/uf3_idx/db
thawedPath = $SPLUNK_DB/uf3_idx/thaweddb

[uf4_idx]
coldPath = $SPLUNK_DB/uf4_idx/colddb
homePath = $SPLUNK_DB/uf4_idx/db
thawedPath = $SPLUNK_DB/uf4_idx/thaweddb

[summary_lineage]
coldPath = $SPLUNK_DB/summary_lineage/colddb
homePath = $SPLUNK_DB/summary_lineage/db
thawedPath = $SPLUNK_DB/summary_lineage/thaweddb
