[Generate Data Lineage Topology]
description = Calculates data flow topology and Loss Ratio based on EPS
cron_schedule = */5 * * * *
enableSched = 1
action.summary_index = 1
action.summary_index._name = summary_lineage
search = index=_internal sourcetype=splunkd (group=tcpin_connections) OR (group=per_sourcetype_thruput series=uf*) \
| eval sourceNode=if(group=="tcpin_connections", coalesce(hostname, sourceIp), host) \
| eval targetNode=if(group=="tcpin_connections", host, null()) \
| eval sourcetype_metric=if(group=="per_sourcetype_thruput", series, null()) \
| stats values(targetNode) as targetNode, sum(eps) as events_per_sec, values(sourcetype_metric) as sourcetype by sourceNode \
| mvexpand targetNode \
| mvexpand sourcetype \
| eval loss_ratio = if(events_per_sec < 0.1, 0.95, 0) \
| table sourceNode, targetNode, events_per_sec, loss_ratio, sourcetype
